src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /*
     * @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email.",
     *     checkMX = true)
         *
         */

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank(message="Email value should not be blank")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Pseudo value should not be blank")
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your pseudo must be at least {{ limit }} characters long",
     *      maxMessage = "Your pseudo cannot be longer than {{ limit }} characters")
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Firstname value should not be blank")
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters")
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Lastname value should not be blank")
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your last name must be at least {{ limit }} characters long",
     *      maxMessage = "Your last name cannot be longer than {{ limit }} characters")
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Sex value should not be blank")
     */
    private $sex;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="Date of birth value should not be blank")
     */
    private $dob;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $profilepicture;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isConnected;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $lastLoginAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isFirstConnection;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lng;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\UserInfos", inversedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Infos;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Slider", inversedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Slider;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPremium;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Rating", inversedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Rating;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Matching", inversedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $matching;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Filter", inversedBy="user", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Filter;


    /**
     * User constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->dob = new \DateTime();
        $this->isConnected = FALSE;
        $this->isFirstConnection = FALSE;
        $this->isPremium = FALSE;
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return User
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    /**
     * @param string $password
     * @return User
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return string|null
     */
    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    /**
     * @param string $pseudo
     * @return User
     */
    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    /**
     * @param string $firstname
     * @return User
     */
    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    /**
     * @param string $lastname
     * @return User
     */
    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * @return string
     */
    public function getSex(): ?string
    {
        return $this->sex;
    }

    /**
     * @param string $sex
     * @return User
     */
    public function setSex(string $sex): self
    {
        $this->sex = $sex;

        return $this;
    }

    /**
     * @return \DateTimeInterface
     */
    public function getDob(): \DateTimeInterface
    {
        return $this->dob;
    }

    /**
     * @param \DateTimeInterface $dob
     * @return User
     */
    public function setDob(\DateTimeInterface $dob): self
    {
        $this->dob = $dob;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getProfilepicture(): ?string
    {
        return $this->profilepicture;
    }

    /**
     * @param string $profilepicture
     * @return User
     */
    public function setProfilepicture(?string $profilepicture): self
    {
        $this->profilepicture = $profilepicture;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsConnected(): ?bool
    {
        return $this->isConnected;
    }

    /**
     * @param bool $isConnected
     * @return User
     */
    public function setIsConnected(bool $isConnected): self
    {
        $this->isConnected = $isConnected;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getLastLoginAt(): ?\DateTimeInterface
    {
        return $this->lastLoginAt;
    }

    /**
     * @param \DateTimeInterface $lastLoginAt
     * @return User
     */
    public function setLastLoginAt(\DateTimeInterface $lastLoginAt): self
    {
        $this->lastLoginAt = $lastLoginAt;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getIsFirstConnection(): ?bool
    {
        return $this->isFirstConnection;
    }

    /**
     * @param bool $isFirstConnection
     * @return User
     */
    public function setIsFirstConnection(bool $isFirstConnection): self
    {
        $this->isFirstConnection = $isFirstConnection;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLat(): ?string
    {
        return $this->lat;
    }

    /**
     * @param string|null $lat
     * @return User
     */
    public function setLat(?string $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getLng(): ?string
    {
        return $this->lng;
    }

    /**
     * @param string|null $lng
     * @return User
     */
    public function setLng(?string $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

    /**
     * @return UserInfos|null
     */
    public function getInfos(): ?UserInfos
    {
        return $this->Infos;
    }

    /**
     * @param UserInfos $Infos
     * @return User
     */

src/Controller/home/HomePageController.php
<?php

namespace App\Controller\home;

use App\Form\UserInfosComplementaryType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;

class HomePageController extends AbstractController
{
    /**
     *
     * imposes a survey at the first connection
     *
     * @Route("/home/page", name="home_page")
     * @param SessionInterface $session
     * @param Request $request
     * @return Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function index(SessionInterface $session, Request $request): Response
    {
        $user = $this->getUser();

        if (!$session->has('isFirstConnection')) {
            $session->set('isFirstConnection', $user->getIsFirstConnection());
        }

        $type = UserInfosComplementaryType::class;
        $form = $this->createForm($type, $user->getInfos());
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $data->setCity(ucfirst(strtolower($data->getCity())));
            $user->setIsfirstConnection(true);
            $user->getRating()->setDomProfileType($data->getProfileDominance());
            $entityManager = $this->getDoctrine()->getManager();

            if ($session->get('isFirstConnection') === false) {
                $user->getRating()->setDomProfileType($user->getInfos()->getProfileDominance());
                $session->set('isFirstConnection', true);
                $entityManager->persist($data);
                $entityManager->persist($user);

                $entityManager->flush();
            }

            $this->redirectToRoute('home_page');
        }
        return $this->render('home/home_page/home_page.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
            'isFirstConnection' => $user->getIsfirstCOnnection(),
        ]);
    }
}

src/Controller/home/MessagesController.php
<?php

namespace App\Controller\home;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/home")
 */
class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="messages")
     */
    public function index()
    {
        return $this->render('home/messages/messages.html.twig', []);
    }
}

src/Controller/home/SliderController.php
<?php

namespace App\Controller\home;

use App\Form\SliderType;
use App\Repository\SliderRepository;
use App\services\StatLibrary;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/home")
 */
class SliderController extends AbstractController
{
    /**
     * @Route("/slider", name="slider")
     * @param Request $request
     * @param SliderRepository $sliderRepository
     * @param StatLibrary $statLibrary
     * @return Response
     */
    public function index(Request $request, SliderRepository $sliderRepository, StatLibrary $statLibrary): Response
    {
        $user = $this->getUser();
        $sliderEntity = $sliderRepository->findOneBy(['id' => $user->getId()]);
        $form = $this->createForm(SliderType::class, $sliderEntity);
        $arrayTmp = explode(",", $sliderEntity->getImg());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid() && count($arrayTmp) < 12) {
            $data = $form->getData();
            $file = $form->get('img')->getData();
            if (!empty($file) && isset($file) && $file !== null) {

                $dir = getcwd() . '/img/' . $user->getPseudo() . '/Slider';
                $fileName = md5(uniqid()) . '.' . $file->guessExtension();
                array_push($arrayTmp, $fileName);
                $stringTmp = implode(',', $arrayTmp);

                $data->setImg($stringTmp);
                $statLibrary->hydrateSLiderAdd($user);

                $em = $this->getDoctrine()->getManager();
                $em->persist($sliderEntity);
                $em->flush();

                try {
                    $file->move($dir, $fileName);
                } catch (FileException $e) {
                    $e->getMessage();
                }
            }
            return $this->redirectToRoute('slider');
        } else {
            if (count($arrayTmp) < 11) {
                $errors = "";
            } else {
                $errors = "Vous avez atteint le nombre maximum  de photos a afficher";
            }
            $tmp = $sliderRepository->find(['id' => $user->getId()]);
            $arrayImg = explode(",", $tmp->getImg());

            return $this->render('home/slider/slider.html.twig', [
                'form' => $form->createView(),
                'arrayImg' => $arrayImg,
                'pseudo' => $user->getPseudo(),
                'errors' => $errors
            ]);
        }
    }

    /**
     *  @Route("/Slider/{img}", name="slider_remove")
     * @param SliderRepository $sliderRepository
     * @param string $img
     * @return Response
     */
    public function removeAction(SliderRepository $sliderRepository,string $img): Response
    {
        $sliderEntity = $sliderRepository->findOneBy(['id' => $this->getUser()->getId()]);
        $arrayTmp = explode(",", $sliderEntity->getImg());

        foreach ($arrayTmp as $key => $value) {
            if ($img === $value) {
                unset($arrayTmp[$key]);
            }
        }
        $stringTmp = implode(',', $arrayTmp);
        $sliderEntity->setImg($stringTmp);
        $em = $this->getDoctrine()->getManager();
        $em->persist($sliderEntity);
        $em->flush();
        unlink(getcwd() . '/img/' . $this->getUser()->getPseudo() . '/Slider/' . $img);
        return $this->redirectToRoute('slider');
    }
}

templates/home/match/match.html.twig
{% extends 'base.html.twig' %}

{% block title %}MATCH CONTROLLER{% endblock %}

{% block body %}
    {% for message in app.flashes('rangeError') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    {% if stopLike != false %}
        <div class="alert alert-warning">
            Il vous reste encore {{ stopLike }} d'attente pour pouvoir liker à nouveaux des profiles
        </div>
    {% endif %}

    {% if sexType is same as('femme') %}
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Filtre
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {{ form_start(form) }}
                {{ form_row(form.rangeAgeMin, {'attr' : {'class' : 'rangeMin'}}) }}<p class="MinVal"></p>
                {{ form_row(form.rangeAgeMax, {'attr' : {'class' : 'rangeMax'}}) }}<p class="MaxVal"></p>
                {{ form_row(form.rangeMaxDistance, {'attr' : {'class' : 'MaxDistance'}}) }}<p class="DistanceVal"></p>
                {{ form_row(form.interest) }}
                {{ form_row(form.lifestyle) }}
                {{ form_row(form.characters) }}
                <button type="submit" class="btn btn-success">Filter</button>
                {{ form_end(form) }}
            </div>
        </div>
    {% else %}
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Filtre
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {{ form_start(form) }}
                {{ form_row(form.rangeAgeMin, {'attr' : {'class' : 'rangeMin'}}) }}<p class="MinVal"></p>
                {{ form_row(form.rangeAgeMax, {'attr' : {'class' : 'rangeMax'}}) }}<p class="MaxVal"></p>
                {{ form_row(form.rangeMaxDistance, {'attr' : {'class' : 'MaxDistance'}}) }}<p class="DistanceVal"></p>
                <div class="d-none"> {#a check coter sécu // voir plus propre#}
                    {{ form_row(form.interest) }}
                    {{ form_row(form.lifestyle) }}
                    {{ form_row(form.characters) }}
                </div>
                <button type="submit" class="btn btn-success">Refresh</button>


                {{ form_end(form) }}
            </div>
        </div>
    {% endif %}

    <div class="row">
        {% for user in userArray %}
            <div class="card col-4 m-4">
                {% if  user.profilePicture != "" %}
                    <a href="#"> <img class="card-img-top"
                                      src="{{ asset("img/"~user.pseudo~"/Profile/"~user.profilePicture) }}"></a>
                {% else %}
                    <img class="card-img-top" src="{{ asset("unknown.png") }}"/>
                {% endif %}
                <div class="card-body">
                    <a href="{{ path('distant_user_display', {'hash': hash,'id' : user.id}) }}"><h5
                                class="card-title"> {{ user.pseudo }}</h5></a>
                    Age : {{ user.dob | age }}
                    <hr>
                    Ville : {{ user.infos.city }}
                    <hr>
                    {% if user.distance >= 1 %}
                        Actuellement à {{ user.distance }}km de votre position
                    {% else %}
                        Actuellement à moins de 1km
                    {% endif %}
                    <hr>
                    <p class="card-text">{{ user.infos.aboutYou }}</p>
                    {% if stopLike == false %}
                        <a href="{{ path('matching_handler_like',{'id' : user.id}) }}" class="btn btn-success">Like</a>
                        <a href="{{ path('matching_handler_dislike',{'id' : user.id}) }}"
                           class="btn btn-danger">Dislike</a>
                    {% endif %}
                    <br>
                    <a href="#">Signaler la photos (ne répresente pas la personne)</a>
                    <br>
                    <a href="#">Signaler Comportement inapproprié</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script>
        $(function () {
            $('.MinVal').text({{ form.vars['data'].rangeAgeMin }});
            $('.MaxVal').text({{ form.vars['data'].rangeAgeMax }});
            $('.DistanceVal').text({{ form.vars['data'].rangeMaxDistance }});

            $('.rangeMin').on('input', function () {
                var $min = $(this).val();
                $('.MinVal').text($min);
            });

            $('.rangeMax').on('input', function () {
                var $max = $(this).val();
                $('.MaxVal').text($max);
            });

            $('.MaxDistance').on('input', function () {
                var $km = $(this).val();
                $('.DistanceVal').text($km);
            });
        });
    </script>
{% endblock %}

templates/home/match/matchDisplay.html.twig
{% extends 'base.html.twig' %}

{% block title %}MATCH CONTROLLER{% endblock %}

{% block body %}MATCH
    <div class="row">
        {% for user in userArray %}
            <div class="card col-4 m-4">
                {% if  user.profilePicture != "" %}
                    <a href="#"> <img class="card-img-top"
                                      src="{{ asset("img/"~user.pseudo~"/Profile/"~user.profilePicture) }}"></a>
                {% else %}
                    <img class="card-img-top" src="{{ asset("unknown.png") }}"/>
                {% endif %}
                <div class="card-body">
                    <a href="{{ path('distant_user_display', {'hash': hash,'id' : user.id}) }}"><h5
                                class="card-title"> {{ user.pseudo }}</h5></a>
                    Age : {{ user.dob | age }}
                    <hr>
                    Ville : {{ user.infos.city }}
                    <hr>
                    {% if user.distance >= 1 %}
                        Actuellement à {{ user.distance }}km de votre position
                    {% else %}
                        Actuellement à moins de 1km
                    {% endif %}
                    <hr>
                    <p class="card-text">{{ user.infos.aboutYou }}</p>
                    <a href="#" class="btn btn-primary">Tchatter</a>
                    <a href="{{ path('delete_match', { 'id' : user.id}) }}" class="btn btn-danger">Supprimer le match</a>
                    <br>
                    <a href="#">Signaler la photos (ne répresente pas la personne)</a>
                    <br>
                    <a href="#">Signaler Comportement inapproprié</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}